server:
  port: 8082
  servlet:
    context-path: /book-shop-order
spring:
  datasource:
    url: jdbc:postgresql://localhost/Order
    driverClassName: org.postgresql.Driver
    username: postgres
    password: vampyrrr9712